# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Masonry' #约束
pod 'AXRatingView', '~> 1.0.6'
pod 'SDWebImage', '~> 4.4.2'
pod 'MJExtension', '~> 3.0.13'

target 'ListDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ListDemo

end
